################################################################
#  Makefile for libcg100 build - with Digital Mars & TurboC++3 #
#              uses compile.cmd by Mastermage  	   			   #
#   libg100.sf.net		- distributed in LGPL				   #
################################################################

########################### Configuration ###############

# appeler avec 'make dm' ou 'make tc' ou 'make' tout court


all: tc dm clean 

clean:
   del *.obj *.bak

tc:
   make -f makefile-tc

dm:
   make -f makefile-dm

